import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));

const cssFiles = [
  "src/styles/00-foundation.css",
  "src/styles/10-auth-setup.css",
  "src/styles/20-dialogs-splashes.css",
  "src/styles/30-nav-hero-layout.css",
  "src/styles/40-modules-sections.css",
  "src/styles/50-library-coursework.css",
  "src/styles/60-topics-dashboard.css",
  "src/styles/70-dashboard-timeline-todo.css",
  "src/styles/80-setup-onboarding-deadlines.css",
  "src/styles/90-responsive-final-overrides.css"
];
const jsFiles = [
  "src/js/00-config-state.js",
  "src/js/10-topic-refresh-fastpath.js",
  "src/js/20-storage-preferences-state.js",
  "src/js/30-links-library-dashboard.js",
  "src/js/40-topic-drag-reorder.js",
  "src/js/50-deadlines-calendar.js",
  "src/js/60-todo-planner.js",
  "src/js/70-module-rendering.js",
  "src/js/80-auth-onboarding-cloud.js",
  "src/js/90-dialogs-actions-boot.js"
];

function bundle(files, banner) {
  return [
    banner,
    ...files.map((file) => {
      const content = readFileSync(join(root, file), 'utf8').trimEnd();
      return `\n\n/* ===== ${file} ===== */\n${content}`;
    }),
    ''
  ].join('\n');
}

mkdirSync(join(root, 'public/generated'), { recursive: true });

writeFileSync(
  join(root, 'public/generated/styles.bundle.css'),
  bundle(cssFiles, '/* Generated by scripts/build-assets.mjs. Edit src/styles/*, not this file. */')
);

writeFileSync(
  join(root, 'public/generated/app.bundle.js'),
  bundle(jsFiles, '/* Generated by scripts/build-assets.mjs. Edit src/js/*, not this file. */')
);

console.log('Synced split source files into public/generated.');
