import { bootApp, syncMobileUxShell, ensureMobileUxShell } from './js/boot.js';
import * as state from './js/state.js';
import * as auth from './js/auth.js';
import * as topics from './js/topics.js';
import * as deadlines from './js/deadlines.js';
import * as rendering from './js/rendering.js';
import * as years from './js/years.js';
import * as dialog from './js/dialog.js';
import * as todo from './js/todo.js';
import * as dashboard from './js/dashboard.js';
import * as grading from './js/grading.js';
import * as library from './js/library.js';
import * as account from './js/account.js';

// ── state.js ──────────────────────────────────────────────────────────────────
window.getStore = state.getStore;
window.getCurrentYear = state.getCurrentYear;
window.refreshActiveYear = state.refreshActiveYear;
window.ensureYearsState = state.ensureYearsState;
window.updateAuthLock = state.updateAuthLock;
window.setAuthLoading = state.setAuthLoading;
window.renderCloudUnavailableGate = state.renderCloudUnavailableGate;
window.isPendingNewAccount = state.isPendingNewAccount;
window.markPendingNewAccount = state.markPendingNewAccount;
window.isMobileViewport = state.isMobileViewport;
window.syncModalScrollLock = state.syncModalScrollLock;
window.syncUndoBaseline = state.syncUndoBaseline;
window.topicSelectionKey = state.topicSelectionKey;
window.applyPreferences = state.applyPreferences;
window.savePreferences = state.savePreferences;
window.setPreference = state.setPreference;
window.setGradingSystemPreference = state.setGradingSystemPreference;
window.editCustomGradeMapping = state.editCustomGradeMapping;
window.toggleCountdownHeaderPreference = state.toggleCountdownHeaderPreference;
window.clearLocalTrackerStorage = state.clearLocalTrackerStorage;
window.setupCourseIfNeeded = state.setupCourseIfNeeded;
window.editCourseProfile = state.editCourseProfile;
window.openPreferences = state.openPreferences;
window.closePreferences = state.closePreferences;
window.togglePreferences = state.togglePreferences;
window.getModuleColourSet = state.getModuleColourSet;
window.isColourCustomisableTheme = state.isColourCustomisableTheme;
window.setModuleColour = state.setModuleColour;
window.getStoredModuleColourHex = state.getStoredModuleColourHex;
window.toggleModuleSection = state.toggleModuleSection;
window.selectSetupTemplate = state.selectSetupTemplate;
window.openCourseSetupModal = state.openCourseSetupModal;
window.closeCourseSetupModal = state.closeCourseSetupModal;
window.saveCourseSetup = state.saveCourseSetup;
window.updateSetupCreditLabel = state.updateSetupCreditLabel;
window.openYearSettingsModal = state.openYearSettingsModal;
window.closeYearSettingsModal = state.closeYearSettingsModal;
window.shouldShowTemplateSplash = state.shouldShowTemplateSplash;
window.showTemplateSplash = state.showTemplateSplash;
window.dismissTemplateSplash = state.dismissTemplateSplash;
window.addCustomBackground = state.addCustomBackground;
window.setBodyBackground = state.setBodyBackground;
window.clearBodyBackground = state.clearBodyBackground;
window.clearCustomBackground = state.clearCustomBackground;
window.openPreferredCalendar = state.openPreferredCalendar;
window.openSelectedCalendar = state.openSelectedCalendar;
window.openCalendarComposer = state.openCalendarComposer;
window.closeCalendarComposer = state.closeCalendarComposer;
window.updateCalendarComposerMode = state.updateCalendarComposerMode;
window.buildCalendarEventFromComposer = state.buildCalendarEventFromComposer;
window.submitCalendarComposer = state.submitCalendarComposer;
window.openYouTube = state.openYouTube;
window.installGradingSystemModalSelector = state.installGradingSystemModalSelector;
window.openGradingSystemGuideModal = state.openGradingSystemGuideModal;
window.closeGradingSystemGuideModal = state.closeGradingSystemGuideModal;
window.chooseGradingSystemFromGuide = state.chooseGradingSystemFromGuide;
window.setActiveGradingGuideRegion = state.setActiveGradingGuideRegion;
window.setGradingGuideViewMode = state.setGradingGuideViewMode;
window.previewGradingGuideRegion = state.previewGradingGuideRegion;
window.clearGradingGuideRegionPreview = state.clearGradingGuideRegionPreview;
window.updateGradingSystemChooserButtons = state.updateGradingSystemChooserButtons;
window.selectTopicRow = state.selectTopicRow;
window.clearTopicSelection = state.clearTopicSelection;
window.handleSelectedTopicDeleteFromKeyboard = state.handleSelectedTopicDeleteFromKeyboard;
window.applyTopicSelectionUI = state.applyTopicSelectionUI;
window.undoLastAction = state.undoLastAction;
window.redoLastAction = state.redoLastAction;

// ── auth.js ───────────────────────────────────────────────────────────────────
window.waitForInitialAuth = auth.waitForInitialAuth;
window.loadCloudSave = auth.loadCloudSave;
window.saveCloudNow = auth.saveCloudNow;
window.saveCloudDebounced = auth.saveCloudDebounced;
window.saveCloud = auth.saveCloud;
window.resetLocalAppState = auth.resetLocalAppState;
window.refreshAppAfterAuth = auth.refreshAppAfterAuth;
window.renderAuthGate = auth.renderAuthGate;
window.renderAuthModal = auth.renderAuthModal;
window.openAuthModal = auth.openAuthModal;
window.closeAuthModal = auth.closeAuthModal;
window.setAuthScreen = auth.setAuthScreen;
window.logoutCloud = auth.logoutCloud;
window.signUpFromModal = auth.signUpFromModal;
window.loginFromModal = auth.loginFromModal;
window.resetPasswordFromModal = auth.resetPasswordFromModal;
window.updatePasswordFromModal = auth.updatePasswordFromModal;
window.togglePasswordVisibility = auth.togglePasswordVisibility;
window.handleAuthKeydown = auth.handleAuthKeydown;
window.setAuthMessage = auth.setAuthMessage;
window.setOnboardingStep = auth.setOnboardingStep;
window.nextOnboardingStep = auth.nextOnboardingStep;
window.previousOnboardingStep = auth.previousOnboardingStep;
window.openOnboardingModal = auth.openOnboardingModal;
window.closeOnboardingModal = auth.closeOnboardingModal;
window.maybeShowWelcomeBackSplash = auth.maybeShowWelcomeBackSplash;
window.isRecoveryFlow = auth.isRecoveryFlow;
window.clearLogoutFlagForSignedInUser = auth.clearLogoutFlagForSignedInUser;
window.markAuthStateKnown = auth.markAuthStateKnown;

// ── topics.js ─────────────────────────────────────────────────────────────────
window.showDeadlineSplash = topics.showDeadlineSplash;
window.closeDeadlineSplash = topics.closeDeadlineSplash;
window.renderBackgroundPicker = topics.renderBackgroundPicker;
window.startTopicDrag = topics.startTopicDrag;
window.dragOverTopic = topics.dragOverTopic;
window.stopTopicDrag = topics.stopTopicDrag;
window.setTopicCheckbox = topics.setTopicCheckbox;
window.setSubtopicCheckbox = topics.setSubtopicCheckbox;
window.refreshTopicStructure = topics.refreshTopicStructure;

// ── deadlines.js ──────────────────────────────────────────────────────────────
window.renderStickyExams = deadlines.renderStickyExams;
window.openDeadlineForm = deadlines.openDeadlineForm;
window.editDeadline = deadlines.editDeadline;
window.closeDeadlineForm = deadlines.closeDeadlineForm;
window.saveDeadlineForm = deadlines.saveDeadlineForm;
window.showDeadlineTab = deadlines.showDeadlineTab;
window.renderDeadlineTimeline = deadlines.renderDeadlineTimeline;
window.updateDeadlineNote = deadlines.updateDeadlineNote;
window.toggleDeadlineComplete = deadlines.toggleDeadlineComplete;
window.openDeadlineTimeline = deadlines.openDeadlineTimeline;
window.closeDeadlineTimeline = deadlines.closeDeadlineTimeline;
window.setupDeadlineBarScrolling = deadlines.setupDeadlineBarScrolling;
window.setDeadlineFormType = deadlines.setDeadlineFormType;
window.updateDeadlineFormMode = deadlines.updateDeadlineFormMode;
window.setDeadlinePriority = deadlines.setDeadlinePriority;
window.setCalendarComposerPriority = deadlines.setCalendarComposerPriority;
window.openDeadlineInCalendarByIndex = deadlines.openDeadlineInCalendarByIndex;

// ── rendering.js ──────────────────────────────────────────────────────────────
window.buildModules = rendering.buildModules;
window.setModuleSort = rendering.setModuleSort;

// ── years.js ──────────────────────────────────────────────────────────────────
window.handleYearDropdown = years.handleYearDropdown;
window.addModuleToCurrentYear = years.addModuleToCurrentYear;
window.closeModuleForm = years.closeModuleForm;
window.updateModuleFormForGradingSystem = years.updateModuleFormForGradingSystem;
window.saveModuleForm = years.saveModuleForm;
window.updateCourseworkComponent = years.updateCourseworkComponent;
window.updateCourseworkSummary = years.updateCourseworkSummary;
window.moveTopicInModule = years.moveTopicInModule;
window.nestTopicUnderTopic = years.nestTopicUnderTopic;
window.startTopicReorder = years.startTopicReorder;
window.allowTopicDrop = years.allowTopicDrop;
window.clearTopicDropState = years.clearTopicDropState;
window.dropTopicReorder = years.dropTopicReorder;
window.endTopicReorder = years.endTopicReorder;
window.allowSubtopicDrop = years.allowSubtopicDrop;
window.dropSubtopicReorder = years.dropSubtopicReorder;
window.addCourseworkComponent = years.addCourseworkComponent;
window.closeCourseworkComponentForm = years.closeCourseworkComponentForm;
window.saveCourseworkComponentForm = years.saveCourseworkComponentForm;
window.commitCourseworkPlaceholder = years.commitCourseworkPlaceholder;
window.addBlankCourseworkComponent = years.addBlankCourseworkComponent;
window.editModuleWeights = years.editModuleWeights;
window.handleModuleTermChange = years.handleModuleTermChange;

// ── dialog.js (deleteCustomBackground overrides topics.js version) ────────────
window.resolveAppDialog = dialog.resolveAppDialog;
window.appConfirm = dialog.appConfirm;
window.appPrompt = dialog.appPrompt;
window.showAppNotice = dialog.showAppNotice;
window.deleteCustomBackground = dialog.deleteCustomBackground;
window.loadAeroTemplate = dialog.loadAeroTemplate;
window.clearModuleMarks = dialog.clearModuleMarks;
window.clearTrackerStorage = dialog.clearTrackerStorage;
window.renderYearSelector = dialog.renderYearSelector;
window.setActiveTermFilter = dialog.setActiveTermFilter;
window.deleteCurrentYear = dialog.deleteCurrentYear;
window.createNewYear = dialog.createNewYear;
window.deleteModuleFromCurrentYear = dialog.deleteModuleFromCurrentYear;
window.editModuleTitle = dialog.editModuleTitle;
window.editModuleCode = dialog.editModuleCode;
window.addTopicToModule = dialog.addTopicToModule;
window.addSubtopicToTopic = dialog.addSubtopicToTopic;
window.moveSubtopicInModule = dialog.moveSubtopicInModule;
window.moveSubtopicToParent = dialog.moveSubtopicToParent;
window.promoteSubtopicToMain = dialog.promoteSubtopicToMain;
window.toggleTopicSubtopics = dialog.toggleTopicSubtopics;
window.editTopicInModule = dialog.editTopicInModule;
window.editSubtopicInModule = dialog.editSubtopicInModule;
window.deleteSelectedTopicsInModule = dialog.deleteSelectedTopicsInModule;
window.deleteCourseworkComponent = dialog.deleteCourseworkComponent;
window.removeExam = dialog.removeExam;

// ── todo.js ───────────────────────────────────────────────────────────────────
window.openTodoPlanner = todo.openTodoPlanner;
window.closeTodoPlanner = todo.closeTodoPlanner;
window.toggleTodoPlanner = todo.toggleTodoPlanner;
window.renderTodoPlanner = todo.renderTodoPlanner;
window.handleTodoTitleKeydown = todo.handleTodoTitleKeydown;
window.handleTodoTitleBlur = todo.handleTodoTitleBlur;
window.toggleTodoDetail = todo.toggleTodoDetail;
window.updateTodoModule = todo.updateTodoModule;
window.handleNewTodoKeydown = todo.handleNewTodoKeydown;
window.handleNewTodoBlur = todo.handleNewTodoBlur;
window.toggleTodoComplete = todo.toggleTodoComplete;
window.updateTodoNote = todo.updateTodoNote;
window.deleteTodoItem = todo.deleteTodoItem;
window.toggleTodoPanelLock = todo.toggleTodoPanelLock;
window.startTodoPanelDrag = todo.startTodoPanelDrag;
window.moveTodoPanelDrag = todo.moveTodoPanelDrag;
window.endTodoPanelDrag = todo.endTodoPanelDrag;
window.applyTodoPanelState = todo.applyTodoPanelState;

// ── dashboard.js ──────────────────────────────────────────────────────────────
window.updateModule = dashboard.updateModule;
window.updateGlobal = dashboard.updateGlobal;
window.formatCountdown = dashboard.formatCountdown;
window.updateDashboard = dashboard.updateDashboard;
window.openDashboard = dashboard.openDashboard;
window.closeDashboard = dashboard.closeDashboard;
window.updatePredictor = dashboard.updatePredictor;
window.renderDashboardTermSummary = dashboard.renderDashboardTermSummary;
window.renderDashboardChart = dashboard.renderDashboardChart;

// ── grading.js ────────────────────────────────────────────────────────────────
window.ensureStoreTermOptions = grading.ensureStoreTermOptions;
window.getActiveTermFilter = grading.getActiveTermFilter;

// ── boot.js ───────────────────────────────────────────────────────────────────
window.syncMobileUxShell = syncMobileUxShell;
window.ensureMobileUxShell = ensureMobileUxShell;

// ── library.js ────────────────────────────────────────────────────────────────
window.openModuleLibrary = library.openModuleLibrary;
window.closeModuleLibrary = library.closeModuleLibrary;
window.handleModuleLibraryKeydown = library.handleModuleLibraryKeydown;
window.updateModuleLibrarySearch = library.updateModuleLibrarySearch;
window.clearModuleLibrarySearch = library.clearModuleLibrarySearch;
window.updateModuleLibraryFilter = library.updateModuleLibraryFilter;
window.setModuleLibraryView = library.setModuleLibraryView;
window.toggleModuleLibraryLinks = library.toggleModuleLibraryLinks;
window.toggleModuleLibraryMaterials = library.toggleModuleLibraryMaterials;
window.openFormulaLink = library.openFormulaLink;
window.openLinkForm = library.openLinkForm;
window.closeLinkForm = library.closeLinkForm;
window.saveLinkForm = library.saveLinkForm;
window.setBlackboardLink = library.setBlackboardLink;
window.openBlackboardLink = library.openBlackboardLink;
window.updateBlackboardButton = library.updateBlackboardButton;
window.setFormulaLink = library.setFormulaLink;
window.deleteFormulaLink = library.deleteFormulaLink;
window.renderFormulaLinks = library.renderFormulaLinks;
window.updateFormulaButton = library.updateFormulaButton;
window.addRelevantLink = library.addRelevantLink;
window.deleteRelevantLink = library.deleteRelevantLink;
window.renderRelevantLinks = library.renderRelevantLinks;
window.togglePinnedLibrarySource = library.togglePinnedLibrarySource;
window.libraryCleanToggleAllSources = library.libraryCleanToggleAllSources;
window.libraryCleanToggleSourceMenu = library.libraryCleanToggleSourceMenu;
window.libraryCleanCloseSourceMenu = library.libraryCleanCloseSourceMenu;
window.setCustomLibraryColour = library.setCustomLibraryColour;
window.libraryCleanAllSources = library.libraryCleanAllSources;
window.libraryCleanSetSource = library.libraryCleanSetSource;
window.libraryCleanSetFolder = library.libraryCleanSetFolder;
window.libraryCleanStepHistory = library.libraryCleanStepHistory;
window.libraryCleanParentFolder = library.libraryCleanParentFolder;
window.libraryCleanSetSortMode = library.libraryCleanSetSortMode;
window.libraryCleanSetViewMode = library.libraryCleanSetViewMode;
window.libraryCleanToggleSort = library.libraryCleanToggleSort;
window.libraryCleanSelect = library.libraryCleanSelect;
window.libraryCleanOpenFolderKey = library.libraryCleanOpenFolderKey;
window.libraryCleanOpenItemKey = library.libraryCleanOpenItemKey;
window.libraryCleanRenameFolderKey = library.libraryCleanRenameFolderKey;
window.libraryCleanDeleteFolderKey = library.libraryCleanDeleteFolderKey;
window.libraryCleanDeleteItemKey = library.libraryCleanDeleteItemKey;
window.libraryCleanEditItemKey = library.libraryCleanEditItemKey;
window.libraryCleanStartItemDrag = library.libraryCleanStartItemDrag;
window.libraryCleanEndItemDrag = library.libraryCleanEndItemDrag;
window.libraryCleanAllowFolderDrop = library.libraryCleanAllowFolderDrop;
window.libraryCleanAllowBreadcrumbDrop = library.libraryCleanAllowBreadcrumbDrop;
window.libraryCleanClearBreadcrumbDrop = library.libraryCleanClearBreadcrumbDrop;
window.libraryCleanDropOnFolder = library.libraryCleanDropOnFolder;
window.libraryCleanDropOnBreadcrumb = library.libraryCleanDropOnBreadcrumb;
window.libraryCleanMoveItemToFolder = library.libraryCleanMoveItemToFolder;
window.libraryCleanMoveItemToPath = library.libraryCleanMoveItemToPath;
window.libraryCleanCreateFolder = library.libraryCleanCreateFolder;
window.libraryCleanOpenAddItem = library.libraryCleanOpenAddItem;
window.openLibraryFolder = library.openLibraryFolder;
window.stepLibraryFolderHistory = library.stepLibraryFolderHistory;
window.createLibraryFolder = library.createLibraryFolder;
window.renameLibraryFolder = library.renameLibraryFolder;
window.deleteLibraryFolder = library.deleteLibraryFolder;
window.openLibraryAdd = library.openLibraryAdd;
window.openLibraryItem = library.openLibraryItem;
window.editLibraryItem = library.editLibraryItem;
window.deleteLibraryItem = library.deleteLibraryItem;
window.createCustomLibrary = library.createCustomLibrary;
window.renameCustomLibrary = library.renameCustomLibrary;
window.deleteCustomLibrary = library.deleteCustomLibrary;
window.unitrackEnhanceLibraryDom = library.unitrackEnhanceLibraryDom;
window.renderModuleLibrary = library.renderModuleLibrary;
window.getUnifiedLibraryRecords = library.getUnifiedLibraryRecords;
window.getUnifiedSelectedFolder = library.getUnifiedSelectedFolder;
window.getSelectedLibraryFolder = library.getSelectedLibraryFolder;
window.getRegisteredLibraryFolders = library.getRegisteredLibraryFolders;

// ── account.js ────────────────────────────────────────────────────────────────
window.renderAccountPanel = account.renderAccountPanel;

// ── Start ─────────────────────────────────────────────────────────────────────
bootApp();
